
services:
  - type: web
    name: earn-money-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: AYET_PUBLISHER_API_KEY
        sync: false
